# Generated by Django 3.1.2 on 2020-10-13 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201013_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_dat',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 13, 38, 59, 704039, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 13, 38, 59, 703666, tzinfo=utc)),
        ),
    ]
