# Generated by Django 3.1.2 on 2020-10-13 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201013_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 14, 4, 26, 624952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_dat',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 14, 4, 26, 625330, tzinfo=utc)),
        ),
    ]
