# Generated by Django 3.1.2 on 2020-10-13 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201013_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_dat',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 14, 5, 4, 491497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 14, 5, 4, 491112, tzinfo=utc)),
        ),
    ]
